// Set the pixel color to an interesting procedural color generated by mixing
// and filtering Perlin noise of different frequencies.
//
// Uniforms:
uniform mat4 view;
uniform mat4 proj;
uniform float animation_seconds;
uniform bool is_moon;
// Inputs:
in vec3 sphere_fs_in;
in vec3 normal_fs_in;
in vec4 pos_fs_in; 
in vec4 view_pos_fs_in; 
// Outputs:
out vec3 color;

// expects: blinn_phong, perlin_noise
void main()
{
  /////////////////////////////////////////////////////////////////////////////
  // Replace with your code 
  float p = 1000; //1000 phong
  float theta = 2 * M_PI * animation_seconds / 8; // one orbit per 8 s

  vec4 light_pos = vec4(6*cos(theta), 5, 6*sin(theta), 1); //light position corresponding to time
  
  
  vec4 light = view * light_pos;

  vec3 light_d = light.xyz - view_pos_fs_in.xyz;
  
  vec3 n = normalize(normal_fs_in); //get n from normal_fs_in and normalize
  vec3 v = normalize(pos_fs_in.xyz); //get v from view_fs_in and normalize
  vec3 l = normalize(light_d); //light direction

  vec3 ka;
  vec3 ks;
  vec3 kd;
  if (is_moon){ //if moon
    ka = vec3(0.01,0.01,0.01);
    kd = vec3(0.5, 0.5, 0.5); //gray
    ks = vec3(1,1,1); //pure white light response
  }
  else{
    ka = vec3(0.01,0.01,0.01);
    kd = vec3(0.1,0.1,1); //blue
    ks = vec3(1,1,1);
  }
  //11.5.3 Turbulence pg 277 textbook
  // perlin_noise will substitute turbulance in the formula
  float noise = abs((1 + sin(50 * (sphere_fs_in.z + perlin_noise(7 * sphere_fs_in)))/3));
  //k1 = 50, k2= 7, w =3, i like that pattern :)

  color = blinn_phong(ka, kd * noise, ks, p, n, v, l);
  /////////////////////////////////////////////////////////////////////////////
}
